# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PBDS241RMw4WzxsWEUtQfZBWG3Cfpc8j
"""

score = input().split()
sum = 0
for p in score:
  sum += int(p)
print(sum//len(score))