# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PBDS241RMw4WzxsWEUtQfZBWG3Cfpc8j
"""

score = input().split()
countF = 0
for i in score:
  countF += int(i)
print(countF//len(score))